language: python
python: 2.7
sudo: true
services: redis-server
addons:
  postgresql: "9.3"
env:
    - TOX_ENV=py27
    - TOX_ENV=py34
    - TOX_ENV=flake8
    - TOX_ENV=docs
before_install:
    # <Kinto>
    - git clone https://github.com/mozilla-services/kinto.git kinto
    - pushd kinto
    - make install-dev
    # Use this cliquet.
    - pip install --ignore-installed -e "..[postgresql,monitoring]"
    # Run in background.
    - cliquet --ini ../cliquet/tests/config/kinto.ini init
    - pserve ../cliquet/tests/config/kinto.ini&
    - popd
    # </Kinto>
install:
    - pip install tox
before_script:
    - psql -c "CREATE DATABASE testdb ENCODING 'UTF8' TEMPLATE template0;" -U postgres
script:
    - tox -e $TOX_ENV
